# Generated by Django 4.0.10 on 2023-11-25 19:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2023, 11, 25, 19, 1, 29, 131659, tzinfo=utc), verbose_name='created at'),
        ),
    ]
