# Generated by Django 4.0.10 on 2023-11-25 19:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='created at'),
        ),
    ]
